import { CreditCard, Landmark, Wallet } from "lucide-react";
import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { createPayment } from "../../api/paymentApi";
import { clearCart } from "../../utils/customerStorage";

// Payment methods are represented as view models to keep rendering logic declarative.
const methods = [
  {
    id: "CARD",
    label: "Credit Card",
    icon: CreditCard,
    description: "Visa, Mastercard, JCB",
  },
  {
    id: "WALLET",
    label: "Digital Wallet",
    icon: Wallet,
    description: "Apple Pay, Google Pay",
  },
  {
    id: "BANK_TRANSFER",
    label: "Bank Transfer",
    icon: Landmark,
    description: "Transfer before appointment",
  },
];

export default function PaymentPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const [method, setMethod] = useState("CARD");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const booking = location.state?.booking;

  // Payment requires a booking generated by the previous screen.
  if (!booking) {
    navigate("/booking");
    return null;
  }

  async function handlePay() {
    try {
      setSubmitting(true);
      setError("");

      const payment = await createPayment({
        bookingId: booking.id,
        method,
      });

      // The cart is cleared only after the backend confirms payment creation successfully.
      clearCart();

      navigate("/my-bookings", {
        state: {
          paymentSuccess: true,
          bookingCode: booking.bookingCode,
          paymentCode: payment.paymentCode,
          email: booking.email,
        },
      });
    } catch (err) {
      setError(err.message || "Cannot create payment.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
      <div className="grid gap-8 lg:grid-cols-[1fr_0.8fr]">
        <section className="rounded-[32px] bg-white p-8 shadow-sm lg:p-10">
          <p className="text-sm font-semibold uppercase tracking-[0.25em] text-rose-500">
            Payment
          </p>
          <h1 className="mt-3 text-4xl font-semibold text-stone-900">
            Choose your payment method
          </h1>

          {error && (
            <div className="mt-6 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
              {error}
            </div>
          )}

          <div className="mt-8 grid gap-4">
            {methods.map((item) => {
              const Icon = item.icon;
              const selected = method === item.id;

              return (
                <button
                  key={item.id}
                  type="button"
                  onClick={() => setMethod(item.id)}
                  className={`flex items-center gap-4 rounded-[28px] border p-5 text-left transition ${
                    selected
                      ? "border-rose-300 bg-rose-50"
                      : "border-stone-200 hover:border-stone-300"
                  }`}
                >
                  <span className="flex h-12 w-12 items-center justify-center rounded-full bg-white text-rose-500 shadow-sm">
                    <Icon className="h-5 w-5" />
                  </span>
                  <span>
                    <span className="block font-semibold text-stone-900">
                      {item.label}
                    </span>
                    <span className="text-sm text-stone-500">
                      {item.description}
                    </span>
                  </span>
                </button>
              );
            })}
          </div>

          <button
            type="button"
            onClick={handlePay}
            disabled={submitting}
            className="mt-8 inline-flex items-center justify-center rounded-full bg-stone-950 px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-rose-500 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {submitting ? "Processing payment..." : "Confirm payment"}
          </button>
        </section>

        <aside className="h-fit rounded-[32px] bg-stone-950 p-8 text-white shadow-sm">
          <h2 className="text-2xl font-semibold">Order summary</h2>
          <div className="mt-6 rounded-[28px] border border-white/10 bg-white/5 p-5 text-sm text-stone-300">
            <p>
              <span className="text-stone-500">Booking code:</span>{" "}
              {booking.bookingCode}
            </p>
            <p className="mt-2">
              <span className="text-stone-500">Customer:</span>{" "}
              {booking.fullName}
            </p>
            <p className="mt-2">
              <span className="text-stone-500">Date:</span>{" "}
              {booking.appointmentDate}
            </p>
            <p className="mt-2">
              <span className="text-stone-500">Time:</span>{" "}
              {booking.appointmentTime}
            </p>
          </div>
          <div className="mt-6 space-y-4 text-sm text-stone-300">
            {(booking.items || []).map((item) => (
              <div
                key={item.serviceId}
                className="flex items-center justify-between gap-3 rounded-3xl bg-white/5 p-4"
              >
                <div>
                  <p className="font-medium text-white">{item.serviceName}</p>
                  <p className="text-xs text-stone-400">
                    {item.quantity} x ${item.unitPrice}
                  </p>
                </div>
                <span>${item.lineTotal}</span>
              </div>
            ))}
          </div>
          <div className="mt-6 border-t border-white/10 pt-6">
            <div className="flex items-center justify-between text-xl font-semibold text-white">
              <span>Total</span>
              <span>${booking.totalAmount}</span>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
